In [ ]:
# ==========================================================
# Project Exodus
# Module 2: SQL & Databases
# Lesson 1: SQL Fundamentals with SQLite
# Author: Olayiwola Oromidayo
# ==========================================================

In [ ]:
import pandas as pd
import sqlite3

In [ ]:
connection = sqlite3.connect("../../Database/logistics.db")

print("Database connected successfully!")

Database connected successfully!

In [ ]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, connection)

              name
0        customers
1          drivers
2           routes
3    customers_new
4  sqlite_sequence
5      drivers_new
6       routes_new
7       deliveries

In [ ]:
import os

os.getcwd()

'c:\\Users\\USER\\Desktop\\Project Exodus\\Python\\Module02_SQL'

In [ ]:
import os

print(os.path.exists("../../Database/logistics.db"))

True

In [ ]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, connection)

              name
0        customers
1          drivers
2           routes
3    customers_new
4  sqlite_sequence
5      drivers_new
6       routes_new
7       deliveries

In [ ]:
import os

os.getcwd()

'c:\\Users\\USER\\Desktop\\Project Exodus\\Python\\Module02_SQL'

In [ ]:
import os

os.listdir("../../")

['.vscode',
 '01 SQL',
 'Dashboards',
 'Database',
 'Datasets',
 'Devops',
 'Documentation',
 'Notes',
 'Portfolio',
 'Power BI',
 'Python',
 'README.md',
 'SQL',
 'Tableau']

In [ ]:
os.listdir("../../Datasets")

['Cleaned', 'External', 'Raw']

In [ ]:
df = pd.read_excel("../../Datasets/Raw/Project_Exodus_Day1_Logistics_Dataset.xlsx")

df.head()

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed
3,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed
4,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed

In [ ]:
df["Profit"] = df["Delivery_Fee"] - df["Fuel_Cost"]

df["Profit_Margin"] = (df["Profit"] / df["Delivery_Fee"]) * 100

df.head()

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
3,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed,1800,72.000000
4,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667

In [ ]:
df.to_sql(
    "deliveries",
    connection,
    if_exists="replace",
    index=False
)

print("Database updated successfully!")

Database updated successfully!

In [ ]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, connection)

              name
0        customers
1          drivers
2           routes
3    customers_new
4  sqlite_sequence
5      drivers_new
6       routes_new
7       deliveries

In [ ]:
#All deliveries

query = """
SELECT *
FROM deliveries;
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
3,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed,1800,72.000000
4,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
5,6,Bisi Fashion,John,Ibadan-Lagos,4000,1400,110,Failed,2600,65.000000
6,7,Tunde Phones,David,Ibadan-Osogbo,2800,800,60,Completed,2000,71.428571
7,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
8,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,90,Completed,1950,60.937500
9,10,Glow Beauty,David,Ibadan-Ilorin,4500,1800,160,Completed,2700,60.000000
10,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615
11,12,Tunde Phones,John,Ibadan-Lagos,3700,1350,105,Completed,2350,63.513514

In [ ]:
#Show delivery ID, driver, route and revenue.

query = """
SELECT
    Delivery_ID,
    Driver,
    Route,
    Delivery_Fee
FROM deliveries;
"""

pd.read_sql(query, connection)

    Delivery_ID Driver          Route  Delivery_Fee
0             1   John   Ibadan-Lagos          3000
1             2   Mary   Ibadan-Abuja          5000
2             3   John   Ibadan-Lagos          3500
3             4  David  Ibadan-Osogbo          2500
4             5   Mary   Ibadan-Abuja          6000
5             6   John   Ibadan-Lagos          4000
6             7  David  Ibadan-Osogbo          2800
7             8   Mary   Ibadan-Abuja          5500
8             9   John   Ibadan-Lagos          3200
9            10  David  Ibadan-Ilorin          4500
10           11   Mary   Ibadan-Abuja          5200
11           12   John   Ibadan-Lagos          3700

In [ ]:
#Show deliveries where fuel cost is above 2000


query = """
SELECT *
FROM deliveries
WHERE Fuel_Cost > 2000;
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
1,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
2,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
3,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615

In [ ]:
#Sorting data


query = """
SELECT *
FROM deliveries
ORDER BY Profit DESC;
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
1,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
2,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615
3,10,Glow Beauty,David,Ibadan-Ilorin,4500,1800,160,Completed,2700,60.000000
4,6,Bisi Fashion,John,Ibadan-Lagos,4000,1400,110,Failed,2600,65.000000
5,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
6,12,Tunde Phones,John,Ibadan-Lagos,3700,1350,105,Completed,2350,63.513514
7,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
8,7,Tunde Phones,David,Ibadan-Osogbo,2800,800,60,Completed,2000,71.428571
9,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,90,Completed,1950,60.937500
10,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
11,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed,1800,72.000000

In [ ]:
#Show the top 3 highest-profit deliveries.

query = """
SELECT *
FROM deliveries
ORDER BY Profit DESC
LIMIT 3;
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
1,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
2,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615

In [ ]:
#Show only customers names.


query = """
SELECT Customer_Name
FROM deliveries;
"""

pd.read_sql(query, connection)

    Customer_Name
0      Ade Stores
1    Bisi Fashion
2      Ade Stores
3   Kemi Ventures
4    Tunde Phones
5    Bisi Fashion
6    Tunde Phones
7      Ade Stores
8   Kemi Ventures
9     Glow Beauty
10    Glow Beauty
11   Tunde Phones

In [ ]:
# Show only routes

query = """
SELECT Route
FROM deliveries;
"""

pd.read_sql(query, connection)

            Route
0    Ibadan-Lagos
1    Ibadan-Abuja
2    Ibadan-Lagos
3   Ibadan-Osogbo
4    Ibadan-Abuja
5    Ibadan-Lagos
6   Ibadan-Osogbo
7    Ibadan-Abuja
8    Ibadan-Lagos
9   Ibadan-Ilorin
10   Ibadan-Abuja
11   Ibadan-Lagos

In [ ]:
#Show only distinct routes, no repetition


query = """
SELECT DISTINCT Route
FROM deliveries;
"""

pd.read_sql(query, connection)

           Route
0   Ibadan-Lagos
1   Ibadan-Abuja
2  Ibadan-Osogbo
3  Ibadan-Ilorin

In [ ]:
#Show all deliveries where Status = 'Completed'


query = """
SELECT*
from deliveries
WHERE Status ="Completed"
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
3,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed,1800,72.000000
4,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
5,7,Tunde Phones,David,Ibadan-Osogbo,2800,800,60,Completed,2000,71.428571
6,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
7,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,90,Completed,1950,60.937500
8,10,Glow Beauty,David,Ibadan-Ilorin,4500,1800,160,Completed,2700,60.000000
9,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615
10,12,Tunde Phones,John,Ibadan-Lagos,3700,1350,105,Completed,2350,63.513514

In [ ]:
query = """
SELECT *
FROM deliveries
WHERE Status = 'Delivered';
"""

pd.read_sql(query, connection)

Empty DataFrame
Columns: [Delivery_ID, Customer_Name, Driver, Route, Delivery_Fee, Fuel_Cost, Delivery_Time_Min, Status, Profit, Profit_Margin]
Index: []

In [ ]:
#How many deliveries have we made?


query = """
SELECT COUNT(*) AS Total_Deliveries
FROM deliveries;
"""

pd.read_sql(query, connection)

   Total_Deliveries
0                12

In [ ]:
#What is our total revenue?




query = """
SELECT SUM(Delivery_Fee) AS Total_Revenue
FROM deliveries;
"""

pd.read_sql(query, connection)

   Total_Revenue
0          48900

In [ ]:
#How much profit did we make?

query = """
SELECT SUM(Profit) AS Total_Profit
FROM deliveries;
"""

pd.read_sql(query, connection)

   Total_Profit
0         29150

In [ ]:
#What is the average delivery time?

query = """
SELECT AVG(Delivery_Time_Min) AS Average_Delivery_Time
FROM deliveries;
"""

pd.read_sql(query, connection)

   Average_Delivery_Time
0             132.083333

In [ ]:
# How many deliveries did each driver complete?

query = """
SELECT
    Driver,
    COUNT(*) AS Total_Deliveries
FROM deliveries
GROUP BY Driver;
"""

pd.read_sql(query, connection)

  Driver  Total_Deliveries
0  David                 3
1   John                 5
2   Mary                 4

In [ ]:
query = """
SELECT
    Driver,
    COUNT(*)
FROM deliveries
GROUP BY Driver;
"""

In [ ]:
#Which routes make the most profit?


query = """
SELECT
    Route,
    SUM(Profit) AS Route_Profit
FROM deliveries
GROUP BY Route
ORDER BY Route_Profit DESC;
"""

pd.read_sql(query, connection)

           Route  Route_Profit
0   Ibadan-Abuja         11750
1   Ibadan-Lagos         10900
2  Ibadan-Osogbo          3800
3  Ibadan-Ilorin          2700

In [ ]:
#Which customers bring the most revenue?


query = """
SELECT
    Customer_Name,
    SUM(Delivery_Fee) AS Customer_Revenue
FROM deliveries
GROUP BY Customer_Name
ORDER BY Customer_Revenue DESC;
"""

pd.read_sql(query, connection)

   Customer_Name  Customer_Revenue
0   Tunde Phones             12500
1     Ade Stores             12000
2    Glow Beauty              9700
3   Bisi Fashion              9000
4  Kemi Ventures              5700

In [ ]:
query = """
SELECT
    Route,
    SUM(Profit) AS Route_Profit
FROM deliveries
GROUP BY Route
ORDER BY Route_Profit DESC;
"""

pd.read_sql(query, connection)

           Route  Route_Profit
0   Ibadan-Abuja         11750
1   Ibadan-Lagos         10900
2  Ibadan-Osogbo          3800
3  Ibadan-Ilorin          2700

In [ ]:
#Which 3 customers give the most profit?


query = """
SELECT
    Customer_Name,
    SUM(Profit) AS Customer_Profit
FROM deliveries
GROUP BY Customer_Name
ORDER BY Customer_Profit DESC
LIMIT 3;
"""

pd.read_sql(query, connection)

  Customer_Name  Customer_Profit
0  Tunde Phones             7750
1    Ade Stores             7100
2   Glow Beauty             5450

In [ ]:
query = """
SELECT
    Driver,
    AVG(Delivery_Time_Min) AS Average_Delivery_Time
FROM deliveries
GROUP BY Driver
ORDER BY Average_Delivery_Time ASC;
"""

pd.read_sql(query, connection)

  Driver  Average_Delivery_Time
0  David              91.666667
1   John             100.000000
2   Mary             202.500000

In [ ]:
#Show only drivers who completed more than 3 deliveries.


query = """
SELECT
    Driver,
    COUNT(*) AS Total_Deliveries
FROM deliveries
GROUP BY Driver
HAVING COUNT(*) > 3;
"""

pd.read_sql(query, connection)

  Driver  Total_Deliveries
0   John                 5
1   Mary                 4

In [ ]:
#Show routes whose total profit is greater than $5,000.

query = """
SELECT
    Route,
    SUM(Profit) AS Route_Profit
FROM deliveries
GROUP BY Route
HAVING SUM(Profit) > 5000
ORDER BY Route_Profit DESC;
"""

pd.read_sql(query, connection)

          Route  Route_Profit
0  Ibadan-Abuja         11750
1  Ibadan-Lagos         10900

In [ ]:
#Show customers whose total revenue exceeds $10,000.


query = """
SELECT
    Customer_Name,
    SUM(Delivery_Fee) AS Revenue
FROM deliveries
GROUP BY Customer_Name
HAVING SUM(Delivery_Fee) > 10000
ORDER BY Revenue DESC;
"""

pd.read_sql(query, connection)

  Customer_Name  Revenue
0  Tunde Phones    12500
1    Ade Stores    12000

In [ ]:
query = """
SELECT
    Route,
    COUNT(*) as Total_Deliveries
FROM deliveries
GROUP BY Route
HAVING (Total_Deliveries) > 2
"""

pd.read_sql(query, connection)

          Route  Total_Deliveries
0  Ibadan-Abuja                 4
1  Ibadan-Lagos                 5

In [ ]:
#Show only drivers who have earned more than $8,000 profit.



query = """
SELECT
    Driver,
    SUM(Delivery_Fee) AS Revenue
FROM deliveries
GROUP BY Driver
HAVING SUM(Delivery_Fee) > 10000
ORDER BY Revenue DESC;
"""

pd.read_sql(query, connection)

  Driver  Revenue
0   Mary    21700
1   John    17400

In [ ]:
#Show only drivers who completed more than 1 deliveries.


query = """
SELECT
    Driver,
    COUNT(*) AS Total_Deliveries
FROM deliveries
GROUP BY Driver
HAVING COUNT(*) > 1;
"""

pd.read_sql(query, connection)

  Driver  Total_Deliveries
0  David                 3
1   John                 5
2   Mary                 4

In [ ]:
#Show completed deliveries that made more than 5,000 profit.


query = """
SELECT *
FROM deliveries
WHERE Status = 'Completed'
AND Profit > 500;
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
3,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed,1800,72.000000
4,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
5,7,Tunde Phones,David,Ibadan-Osogbo,2800,800,60,Completed,2000,71.428571
6,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
7,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,90,Completed,1950,60.937500
8,10,Glow Beauty,David,Ibadan-Ilorin,4500,1800,160,Completed,2700,60.000000
9,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615
10,12,Tunde Phones,John,Ibadan-Lagos,3700,1350,105,Completed,2350,63.513514

In [ ]:
#Show deliveries made by John or Mary.

query = """
SELECT *
FROM deliveries
WHERE Driver = 'John'
OR Driver = 'Mary';
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
3,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
4,6,Bisi Fashion,John,Ibadan-Lagos,4000,1400,110,Failed,2600,65.000000
5,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
6,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,90,Completed,1950,60.937500
7,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615
8,12,Tunde Phones,John,Ibadan-Lagos,3700,1350,105,Completed,2350,63.513514

#IN operator

In [ ]:
query = """
SELECT *
FROM deliveries
WHERE Driver IN ('John', 'Mary', 'David');
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
3,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed,1800,72.000000
4,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
5,6,Bisi Fashion,John,Ibadan-Lagos,4000,1400,110,Failed,2600,65.000000
6,7,Tunde Phones,David,Ibadan-Osogbo,2800,800,60,Completed,2000,71.428571
7,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
8,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,90,Completed,1950,60.937500
9,10,Glow Beauty,David,Ibadan-Ilorin,4500,1800,160,Completed,2700,60.000000
10,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615
11,12,Tunde Phones,John,Ibadan-Lagos,3700,1350,105,Completed,2350,63.513514

In [ ]:
#Show deliveries that took between 30 and 60 minutes.

query = """
SELECT *
FROM deliveries
WHERE Delivery_Time_Min BETWEEN 30 AND 60;
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed,1800,72.000000
1,7,Tunde Phones,David,Ibadan-Osogbo,2800,800,60,Completed,2000,71.428571

Using LIKE

In [ ]:
#Find customers whose names start with A.


query = """
SELECT *
FROM deliveries
WHERE Customer_Name LIKE 'A%';
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
2,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636

In [ ]:
#Customers whose names start and end with A


query = """
SELECT *
FROM deliveries
WHERE Customer_Name LIKE 'A%A';
"""

pd.read_sql(query, connection)

Empty DataFrame
Columns: [Delivery_ID, Customer_Name, Driver, Route, Delivery_Fee, Fuel_Cost, Delivery_Time_Min, Status, Profit, Profit_Margin]
Index: []

In [ ]:
#Customers whose names contain stores
query = """
SELECT *
FROM deliveries
WHERE Customer_Name LIKE '%stores%';
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
2,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636

In [ ]:
#Show all deliveries where: Status is Completed and  Profit is greater than 5,000


query = """

SELECT *
FROM deliveries
WHERE Status = 'Completed'
AND Profit > 500
"""


pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
3,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed,1800,72.000000
4,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
5,7,Tunde Phones,David,Ibadan-Osogbo,2800,800,60,Completed,2000,71.428571
6,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
7,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,90,Completed,1950,60.937500
8,10,Glow Beauty,David,Ibadan-Ilorin,4500,1800,160,Completed,2700,60.000000
9,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615
10,12,Tunde Phones,John,Ibadan-Lagos,3700,1350,105,Completed,2350,63.513514

In [ ]:
query = """
SELECT *
FROM deliveries
WHERE Driver IN ('John', 'Mary');
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
3,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
4,6,Bisi Fashion,John,Ibadan-Lagos,4000,1400,110,Failed,2600,65.000000
5,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
6,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,90,Completed,1950,60.937500
7,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615
8,12,Tunde Phones,John,Ibadan-Lagos,3700,1350,105,Completed,2350,63.513514

In [ ]:
#Show deliveries that took between: 40 minutes  90 minutes

query = """

SELECT* 
from deliveries
 WHERE Delivery_Time_Min BETWEEN 40 AND 90;
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed,1800,72.000000
1,7,Tunde Phones,David,Ibadan-Osogbo,2800,800,60,Completed,2000,71.428571
2,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,90,Completed,1950,60.937500

In [ ]:
query = """
SELECT
    MAX(Profit) AS Highest_Profit
FROM deliveries;
"""

pd.read_sql(query, connection)

   Highest_Profit
0            3400

In [ ]:
import pandas as pd
import matplotlib as plt

In [ ]:
query = """
CREATE TABLE customers AS
SELECT DISTINCT
    Customer_Name
FROM deliveries;
"""

connection.execute(query)

print("Customers table created!")

OperationalError: table customers already exists

In [ ]:
query = """
SELECT *
FROM customers;
"""

pd.read_sql(query, connection)

   Customer_Name
0     Ade Stores
1   Bisi Fashion
2  Kemi Ventures
3   Tunde Phones
4    Glow Beauty

In [ ]:
query = """
SELECT COUNT(*) AS Total_Customers
FROM customers;
"""

pd.read_sql(query, connection)

   Total_Customers
0                5

In [ ]:
query = """
CREATE TABLE drivers AS
SELECT DISTINCT
    Driver
FROM deliveries;
"""

connection.execute(query)

print("Drivers table created!")

Drivers table created!

In [ ]:
query = """
SELECT *
FROM drivers;
"""

pd.read_sql(query, connection)

  Driver
0   John
1   Mary
2  David

In [ ]:
query = """
SELECT COUNT(*) AS Total_Drivers
FROM drivers;
"""

pd.read_sql(query, connection)

   Total_Drivers
0              3

In [ ]:
query = """
SELECT *
FROM routes;
"""

pd.read_sql(query, connection)

           Route
0   Ibadan-Lagos
1   Ibadan-Abuja
2  Ibadan-Osogbo
3  Ibadan-Ilorin

In [ ]:
query = """
CREATE TABLE customers_new (
    Customer_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Customer_Name TEXT UNIQUE
);
"""

connection.execute(query)

print("customers_new created!")

customers_new created!

In [ ]:
query = """
INSERT INTO customers_new (Customer_Name)
SELECT DISTINCT Customer_Name
FROM deliveries;
"""

connection.execute(query)

print("Customers inserted!")

Customers inserted!

In [ ]:
query = """
SELECT *
FROM customers_new;
"""

pd.read_sql(query, connection)

   Customer_ID  Customer_Name
0            1     Ade Stores
1            2   Bisi Fashion
2            3  Kemi Ventures
3            4   Tunde Phones
4            5    Glow Beauty

In [ ]:
query = """
CREATE TABLE drivers_new (
    Driver_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Driver TEXT UNIQUE
);
"""

connection.execute(query)

print("drivers_new created!")

NameError: name 'connection' is not defined

In [ ]:
query = """
INSERT INTO drivers_new (Driver)
SELECT DISTINCT Driver
FROM deliveries;
"""

connection.execute(query)

print("Drivers inserted!")

IntegrityError: UNIQUE constraint failed: drivers_new.Driver

In [ ]:
query = """
SELECT *
FROM drivers_new;
"""

pd.read_sql(query, connection)

   Driver_ID Driver
0          1   John
1          2   Mary
2          3  David

In [ ]:
query = """
CREATE TABLE routes_new (
    Route_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Route TEXT UNIQUE
);
"""

connection.execute(query)

print("routes_new created!")

routes_new created!

In [ ]:
query = """
INSERT INTO routes_new (Route)
SELECT DISTINCT Route
FROM deliveries;
"""

connection.execute(query)

print("Routes inserted!")

Routes inserted!

In [ ]:
query = """
SELECT *
FROM routes_new;
"""

pd.read_sql(query, connection)

   Route_ID          Route
0         1   Ibadan-Lagos
1         2   Ibadan-Abuja
2         3  Ibadan-Osogbo
3         4  Ibadan-Ilorin

In [ ]:
query = """
SELECT
    d.Delivery_ID,
    c.Customer_ID,
    c.Customer_Name,
    d.Delivery_Fee,
    d.Profit
FROM deliveries d
INNER JOIN customers_new c
ON d.Customer_Name = c.Customer_Name;
"""

pd.read_sql(query, connection)

    Delivery_ID  Customer_ID  Customer_Name  Delivery_Fee  Profit
0             1            1     Ade Stores          3000    1800
1             2            2   Bisi Fashion          5000    2500
2             3            1     Ade Stores          3500    2200
3             4            3  Kemi Ventures          2500    1800
4             5            4   Tunde Phones          6000    3400
5             6            2   Bisi Fashion          4000    2600
6             7            4   Tunde Phones          2800    2000
7             8            1     Ade Stores          5500    3100
8             9            3  Kemi Ventures          3200    1950
9            10            5    Glow Beauty          4500    2700
10           11            5    Glow Beauty          5200    2750
11           12            4   Tunde Phones          3700    2350

In [ ]:
query = """
SELECT
    d.Delivery_ID,
    c.Customer_Name,
    dr.Driver,
    d.Delivery_Fee,
    d.Profit
FROM deliveries d

INNER JOIN customers_new c
ON d.Customer_Name = c.Customer_Name

INNER JOIN drivers_new dr
ON d.Driver = dr.Driver;
"""

pd.read_sql(query, connection)

    Delivery_ID  Customer_Name Driver  Delivery_Fee  Profit
0             1     Ade Stores   John          3000    1800
1             2   Bisi Fashion   Mary          5000    2500
2             3     Ade Stores   John          3500    2200
3             4  Kemi Ventures  David          2500    1800
4             5   Tunde Phones   Mary          6000    3400
5             6   Bisi Fashion   John          4000    2600
6             7   Tunde Phones  David          2800    2000
7             8     Ade Stores   Mary          5500    3100
8             9  Kemi Ventures   John          3200    1950
9            10    Glow Beauty  David          4500    2700
10           11    Glow Beauty   Mary          5200    2750
11           12   Tunde Phones   John          3700    2350

In [ ]:
query = """
SELECT
    d.Delivery_ID,
    c.Customer_Name,
    dr.Driver,
    r.Route,
    d.Delivery_Fee,
    d.Fuel_Cost,
    d.Profit
FROM deliveries d

INNER JOIN customers_new c
ON d.Customer_Name = c.Customer_Name

INNER JOIN drivers_new dr
ON d.Driver = dr.Driver

INNER JOIN routes_new r
ON d.Route = r.Route;
"""

pd.read_sql(query, connection)

NameError: name 'pd' is not defined

In [ ]:
query = """
SELECT
    dr.Driver,
    SUM(d.Profit) AS Total_Profit
FROM deliveries d

INNER JOIN drivers_new dr
ON d.Driver = dr.Driver

GROUP BY dr.Driver

ORDER BY Total_Profit DESC;
"""

#pd.read_sql(query, connection)

  Driver  Total_Profit
0   Mary         11750
1   John         10900
2  David          6500

In [ ]:
#Route with the highest profit
query = """
SELECT
    r.Route,
    SUM(d.Delivery_Fee) AS Total_Revenue
FROM deliveries d

INNER JOIN routes_new r
ON d.Route = r.Route

GROUP BY r.Route

ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, connection)

DatabaseError: Execution failed on sql '
SELECT
    r.Route,
    SUM(d.Delivery_Fee) AS Total_Revenue
FROM deliveries d

INNER JOIN routes_new r
ON d.Route = r.Route

GROUP BY r.Route

ORDER BY Total_Revenue DESC;
': no such table: routes_new

In [ ]:
# Route with the highest revenue

query = """
SELECT
    r.Route,
    SUM(d.Delivery_Fee) AS Total_Revenue
FROM deliveries d

INNER JOIN routes_new r
ON d.Route = r.Route

GROUP BY r.Route

ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, connection)

DatabaseError: Execution failed on sql '
SELECT
    r.Route,
    SUM(d.Delivery_Fee) AS Total_Revenue
FROM deliveries d

INNER JOIN routes_new r
ON d.Route = r.Route

GROUP BY r.Route

ORDER BY Total_Revenue DESC;
': no such table: routes_new

In [ ]:
query = """
SELECT name
FROM sqlite_master
WHERE type = 'table';
"""

pd.read_sql(query, connection)

              name
0       deliveries
1        customers
2          drivers
3           routes
4    customers_new
5  sqlite_sequence

In [ ]:
query = """
CREATE TABLE drivers_new (
    Driver_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Driver TEXT UNIQUE
);
"""

connection.execute(query)

query = """
INSERT INTO drivers_new (Driver)
SELECT DISTINCT Driver
FROM deliveries;
"""

connection.execute(query)

print("drivers_new created successfully!")

drivers_new created successfully!

In [ ]:
query = """
SELECT *
FROM drivers_new;
"""

pd.read_sql(query, connection)

Empty DataFrame
Columns: [Driver_ID, Driver]
Index: []

In [ ]:
query = """
CREATE TABLE routes_new (
    Route_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Route TEXT UNIQUE
);
"""

connection.execute(query)

query = """
INSERT INTO routes_new (Route)
SELECT DISTINCT Route
FROM deliveries;
"""

connection.execute(query)

print("routes_new created successfully!")

OperationalError: table routes_new already exists

In [ ]:
query = """
SELECT *
FROM routes_new;
"""

pd.read_sql(query, connection)

   Route_ID          Route
0         1   Ibadan-Lagos
1         2   Ibadan-Abuja
2         3  Ibadan-Osogbo
3         4  Ibadan-Ilorin

In [ ]:
query = """
SELECT name
FROM sqlite_master
WHERE type = 'table';
"""

pd.read_sql(query, connection)

              name
0       deliveries
1        customers
2          drivers
3           routes
4    customers_new
5  sqlite_sequence
6      drivers_new
7       routes_new

In [ ]:
query = """
SELECT
    r.Route,
    SUM(d.Delivery_Fee) AS Total_Revenue
FROM deliveries d

INNER JOIN routes_new r
ON d.Route = r.Route

GROUP BY r.Route

ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, connection)

           Route  Total_Revenue
0   Ibadan-Abuja          21700
1   Ibadan-Lagos          17400
2  Ibadan-Osogbo           5300
3  Ibadan-Ilorin           4500

In [ ]:
query = """
SELECT
    dr.Driver,
    r.Route,
    SUM(d.Profit) AS Total_Profit
FROM deliveries d

INNER JOIN drivers_new dr
ON d.Driver = dr.Driver

INNER JOIN routes_new r
ON d.Route = r.Route

GROUP BY
    dr.Driver,
    r.Route

ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, connection)

  Driver          Route  Total_Profit
0   Mary   Ibadan-Abuja         11750
1   John   Ibadan-Lagos         10900
2  David  Ibadan-Osogbo          3800
3  David  Ibadan-Ilorin          2700

In [ ]:
query = """
SELECT *
FROM drivers_new;
"""

pd.read_sql(query, connection)

NameError: name 'pd' is not defined

In [ ]:
query = """
SELECT DISTINCT Route
FROM deliveries;
"""

pd.read_sql(query, connection)

           Route
0   Ibadan-Lagos
1   Ibadan-Abuja
2  Ibadan-Osogbo
3  Ibadan-Ilorin

In [ ]:
query = """
SELECT DISTINCT Driver
FROM deliveries;
"""

pd.read_sql(query, connection)

  Driver
0   John
1   Mary
2  David

In [ ]:
query = """
SELECT DISTINCT Driver
FROM drivers_new;
"""

pd.read_sql(query, connection)

Empty DataFrame
Columns: [Driver]
Index: []

In [ ]:
query = """
INSERT INTO drivers_new (Driver)
SELECT DISTINCT Driver
FROM deliveries;
"""

connection.execute(query)
connection.commit()

print("Drivers populated!")

Drivers populated!

In [ ]:
query = """
SELECT *
FROM drivers_new;
"""

pd.read_sql(query, connection)

   Driver_ID Driver
0          1   John
1          2   Mary
2          3  David

In [ ]:
query = """
INSERT INTO routes_new (Route)
SELECT DISTINCT Route
FROM deliveries;
"""

connection.execute(query)
connection.commit()

print("Routes populated!")

IntegrityError: UNIQUE constraint failed: routes_new.Route

In [ ]:
query = """
SELECT *
FROM routes_new;
"""

pd.read_sql(query, connection)

   Route_ID          Route
0         1   Ibadan-Lagos
1         2   Ibadan-Abuja
2         3  Ibadan-Osogbo
3         4  Ibadan-Ilorin

In [ ]:
query = """
SELECT *
FROM drivers_new;
"""

pd.read_sql(query, connection)

   Driver_ID Driver
0          1   John
1          2   Mary
2          3  David

In [ ]:
query = """
SELECT
    r.Route,
    SUM(d.Delivery_Fee) AS Total_Revenue
FROM deliveries d

INNER JOIN routes_new r
ON d.Route = r.Route

GROUP BY r.Route

ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, connection)

           Route  Total_Revenue
0   Ibadan-Abuja          21700
1   Ibadan-Lagos          17400
2  Ibadan-Osogbo           5300
3  Ibadan-Ilorin           4500

In [ ]:
SELECT * FROM routes_new;

SyntaxError: invalid syntax (342199198.py, line 1)

In [ ]:
query = """
SELECT *
FROM routes_new;
"""

pd.read_sql(query, connection)

   Route_ID          Route
0         1   Ibadan-Lagos
1         2   Ibadan-Abuja
2         3  Ibadan-Osogbo
3         4  Ibadan-Ilorin

In [ ]:
query = """
SELECT *
FROM customers_new;
"""

pd.read_sql(query, connection)

Empty DataFrame
Columns: [Customer_ID, Customer_Name]
Index: []

In [ ]:
query = """
SELECT *
FROM drivers_new;
"""

pd.read_sql(query, connection)

   Driver_ID Driver
0          1   John
1          2   Mary
2          3  David

In [ ]:
query = """
SELECT *
FROM routes_new;
"""

pd.read_sql(query, connection)

   Route_ID          Route
0         1   Ibadan-Lagos
1         2   Ibadan-Abuja
2         3  Ibadan-Osogbo
3         4  Ibadan-Ilorin

In [ ]:
query = """
SELECT DISTINCT Customer_Name
FROM deliveries;
"""

pd.read_sql(query, connection)

   Customer_Name
0     Ade Stores
1   Bisi Fashion
2  Kemi Ventures
3   Tunde Phones
4    Glow Beauty

In [ ]:
query = """
INSERT INTO customers_new (Customer_Name)
SELECT DISTINCT Customer_Name
FROM deliveries;
"""

connection.execute(query)
connection.commit()

print("Customers populated!")

Customers populated!

In [ ]:
query = """
SELECT *
FROM customers_new;
"""

pd.read_sql(query, connection)

   Customer_ID  Customer_Name
0            1     Ade Stores
1            2   Bisi Fashion
2            3  Kemi Ventures
3            4   Tunde Phones
4            5    Glow Beauty

In [ ]:
query = """
SELECT
    d.Delivery_ID,
    c.Customer_Name,
    dr.Driver,
    r.Route,
    d.Delivery_Fee,
    d.Fuel_Cost,
    d.Profit
FROM deliveries d

INNER JOIN customers_new c
ON d.Customer_Name = c.Customer_Name

INNER JOIN drivers_new dr
ON d.Driver = dr.Driver

INNER JOIN routes_new r
ON d.Route = r.Route;
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Profit
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,1800
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,2500
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,2200
3,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,1800
4,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,3400
5,6,Bisi Fashion,John,Ibadan-Lagos,4000,1400,2600
6,7,Tunde Phones,David,Ibadan-Osogbo,2800,800,2000
7,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,3100
8,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,1950
9,10,Glow Beauty,David,Ibadan-Ilorin,4500,1800,2700
10,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,2750
11,12,Tunde Phones,John,Ibadan-Lagos,3700,1350,2350

In [ ]:
#Subquery


query = """
SELECT *
FROM deliveries
WHERE Profit >
(
    SELECT AVG(Profit)
    FROM deliveries
);
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
1,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
2,6,Bisi Fashion,John,Ibadan-Lagos,4000,1400,110,Failed,2600,65.000000
3,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
4,10,Glow Beauty,David,Ibadan-Ilorin,4500,1800,160,Completed,2700,60.000000
5,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615

In [ ]:

query = """
SELECT
    dr.Driver,
    SUM(d.Profit) AS Total_Profit
FROM deliveries d

INNER JOIN drivers_new dr
ON d.Driver = dr.Driver

GROUP BY dr.Driver

HAVING SUM(d.Profit) >
(
    SELECT AVG(Driver_Profit)
    FROM
    (
        SELECT
            SUM(Profit) AS Driver_Profit
        FROM deliveries
        GROUP BY Driver
    )
)

ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, connection)

  Driver  Total_Profit
0   Mary         11750
1   John         10900

In [ ]:
query = """

SELECT
    SUM(Profit) AS Driver_Profit
FROM deliveries
GROUP BY Driver

"""
pd.read_sql(query, connection)

   Driver_Profit
0           6500
1          10900
2          11750

WINDOW FUNCTIONS

In [ ]:
query = """
SELECT
    Delivery_ID,
    Driver,
    Profit,

    SUM(Profit)
    OVER(PARTITION BY Driver)
    AS Driver_Total_Profit

FROM deliveries;
"""

pd.read_sql(query, connection)

    Delivery_ID Driver  Profit  Driver_Total_Profit
0             4  David    1800                 6500
1             7  David    2000                 6500
2            10  David    2700                 6500
3             1   John    1800                10900
4             3   John    2200                10900
5             6   John    2600                10900
6             9   John    1950                10900
7            12   John    2350                10900
8             2   Mary    2500                11750
9             5   Mary    3400                11750
10            8   Mary    3100                11750
11           11   Mary    2750                11750

In [ ]:
query = """
SELECT
    Driver,
    SUM(Profit) AS Total_Profit,

    RANK() OVER
    (
        ORDER BY SUM(Profit) DESC
    ) AS Profit_Rank

FROM deliveries

GROUP BY Driver;
"""

pd.read_sql(query, connection)

  Driver  Total_Profit  Profit_Rank
0   Mary         11750            1
1   John         10900            2
2  David          6500            3

In [ ]:
query = """
SELECT
    Delivery_ID,
    Driver,
    Profit,
    SUM(Profit) OVER(PARTITION BY Driver) AS Driver_Total_Profit
FROM deliveries;
"""

pd.read_sql(query, connection)

    Delivery_ID Driver  Profit  Driver_Total_Profit
0             4  David    1800                 6500
1             7  David    2000                 6500
2            10  David    2700                 6500
3             1   John    1800                10900
4             3   John    2200                10900
5             6   John    2600                10900
6             9   John    1950                10900
7            12   John    2350                10900
8             2   Mary    2500                11750
9             5   Mary    3400                11750
10            8   Mary    3100                11750
11           11   Mary    2750                11750

In [ ]:
query = """
SELECT
    Driver,
    SUM(Profit) AS Total_Profit,
    RANK() OVER(ORDER BY SUM(Profit) DESC) AS Profit_Rank
FROM deliveries
GROUP BY Driver;
"""

pd.read_sql(query, connection)

  Driver  Total_Profit  Profit_Rank
0   Mary         11750            1
1   John         10900            2
2  David          6500            3

In [ ]:
import pandas as pd
import matplotlib as plt
import os

In [ ]:
query = """
SELECT
    Delivery_ID,
    Driver,
    Profit,
    ROW_NUMBER() OVER(ORDER BY Profit DESC) AS Row_Num
FROM deliveries;
"""

pd.read_sql(query, connection)

    Delivery_ID Driver  Profit  Row_Num
0             5   Mary    3400        1
1             8   Mary    3100        2
2            11   Mary    2750        3
3            10  David    2700        4
4             6   John    2600        5
5             2   Mary    2500        6
6            12   John    2350        7
7             3   John    2200        8
8             7  David    2000        9
9             9   John    1950       10
10            1   John    1800       11
11            4  David    1800       12

In [ ]:
query = """
SELECT
    Driver,
    SUM(Profit) AS Total_Profit,
    RANK() OVER(ORDER BY SUM(Profit) DESC) AS Profit_Rank
FROM deliveries
GROUP BY Driver;
"""

pd.read_sql(query, connection)

  Driver  Total_Profit  Profit_Rank
0   Mary         11750            1
1   John         10900            2
2  David          6500            3

In [ ]:
#Rank drivers by total profit

query = """
SELECT
    Driver,
    SUM(Profit) AS Total_Profit,
    RANK() OVER(ORDER BY SUM(Profit) DESC) AS Profit_Rank
FROM deliveries
GROUP BY Driver;
"""

pd.read_sql(query, connection)

  Driver  Total_Profit  Profit_Rank
0   Mary         11750            1
1   John         10900            2
2  David          6500            3

Total profit per driver using SUM() OVER()

In [ ]:
query = """
SELECT
    Delivery_ID,
    Driver,
    Profit,
    SUM(Profit) OVER(PARTITION BY Driver) AS Driver_Total_Profit
FROM deliveries;
"""

pd.read_sql(query, connection)

    Delivery_ID Driver  Profit  Driver_Total_Profit
0             4  David    1800                 6500
1             7  David    2000                 6500
2            10  David    2700                 6500
3             1   John    1800                10900
4             3   John    2200                10900
5             6   John    2600                10900
6             9   John    1950                10900
7            12   John    2350                10900
8             2   Mary    2500                11750
9             5   Mary    3400                11750
10            8   Mary    3100                11750
11           11   Mary    2750                11750

In [ ]:
#Number deliveries from highest profit to lowest

query = """
SELECT
    Delivery_ID,
    Driver,
    Profit,
    ROW_NUMBER() OVER(ORDER BY Profit DESC) AS Row_Num
FROM deliveries;
"""

pd.read_sql(query, connection)

    Delivery_ID Driver  Profit  Row_Num
0             5   Mary    3400        1
1             8   Mary    3100        2
2            11   Mary    2750        3
3            10  David    2700        4
4             6   John    2600        5
5             2   Mary    2500        6
6            12   John    2350        7
7             3   John    2200        8
8             7  David    2000        9
9             9   John    1950       10
10            1   John    1800       11
11            4  David    1800       12

In [ ]:
#Number deliveries from highest profit to lowest

query = """
SELECT
    Delivery_ID,
    Profit,
    ROW_NUMBER() OVER(ORDER BY Profit DESC) AS Row_Num
FROM deliveries;
"""

pd.read_sql(query, connection)

    Delivery_ID  Profit  Row_Num
0             5    3400        1
1             8    3100        2
2            11    2750        3
3            10    2700        4
4             6    2600        5
5             2    2500        6
6            12    2350        7
7             3    2200        8
8             7    2000        9
9             9    1950       10
10            1    1800       11
11            4    1800       12

DATA CLEANING WITH SQL

In [ ]:
query = """
SELECT
    Customer_Name,
    UPPER(Customer_Name) AS Upper_Name
FROM deliveries;
"""

pd.read_sql(query, connection)

    Customer_Name     Upper_Name
0      Ade Stores     ADE STORES
1    Bisi Fashion   BISI FASHION
2      Ade Stores     ADE STORES
3   Kemi Ventures  KEMI VENTURES
4    Tunde Phones   TUNDE PHONES
5    Bisi Fashion   BISI FASHION
6    Tunde Phones   TUNDE PHONES
7      Ade Stores     ADE STORES
8   Kemi Ventures  KEMI VENTURES
9     Glow Beauty    GLOW BEAUTY
10    Glow Beauty    GLOW BEAUTY
11   Tunde Phones   TUNDE PHONES

In [ ]:
query = """
SELECT
    Customer_Name,
    LOWER(Customer_Name) AS Lower_Name
FROM deliveries;
"""

pd.read_sql(query, connection)

    Customer_Name     Lower_Name
0      Ade Stores     ade stores
1    Bisi Fashion   bisi fashion
2      Ade Stores     ade stores
3   Kemi Ventures  kemi ventures
4    Tunde Phones   tunde phones
5    Bisi Fashion   bisi fashion
6    Tunde Phones   tunde phones
7      Ade Stores     ade stores
8   Kemi Ventures  kemi ventures
9     Glow Beauty    glow beauty
10    Glow Beauty    glow beauty
11   Tunde Phones   tunde phones

In [ ]:
query = """
SELECT*
FROM deliveries;
"""

pd.read_sql(query, connection)

,Delivery_ID,Customer_Name,Driver,Route,Delivery_Fee,Fuel_Cost,Delivery_Time_Min,Status,Profit,Profit_Margin
0,1,Ade Stores,John,Ibadan-Lagos,3000,1200,95,Completed,1800,60.000000
1,2,Bisi Fashion,Mary,Ibadan-Abuja,5000,2500,210,Completed,2500,50.000000
2,3,Ade Stores,John,Ibadan-Lagos,3500,1300,100,Completed,2200,62.857143
3,4,Kemi Ventures,David,Ibadan-Osogbo,2500,700,55,Completed,1800,72.000000
4,5,Tunde Phones,Mary,Ibadan-Abuja,6000,2600,205,Completed,3400,56.666667
5,6,Bisi Fashion,John,Ibadan-Lagos,4000,1400,110,Failed,2600,65.000000
6,7,Tunde Phones,David,Ibadan-Osogbo,2800,800,60,Completed,2000,71.428571
7,8,Ade Stores,Mary,Ibadan-Abuja,5500,2400,195,Completed,3100,56.363636
8,9,Kemi Ventures,John,Ibadan-Lagos,3200,1250,90,Completed,1950,60.937500
9,10,Glow Beauty,David,Ibadan-Ilorin,4500,1800,160,Completed,2700,60.000000
10,11,Glow Beauty,Mary,Ibadan-Abuja,5200,2450,200,Completed,2750,52.884615
11,12,Tunde Phones,John,Ibadan-Lagos,3700,1350,105,Completed,2350,63.513514

In [ ]:
query = """
SELECT
    Customer_Name,
    LOWER(Customer_Name) AS Lower_Name
FROM deliveries;
"""

pd.read_sql(query, connection)

    Customer_Name     Lower_Name
0      Ade Stores     ade stores
1    Bisi Fashion   bisi fashion
2      Ade Stores     ade stores
3   Kemi Ventures  kemi ventures
4    Tunde Phones   tunde phones
5    Bisi Fashion   bisi fashion
6    Tunde Phones   tunde phones
7      Ade Stores     ade stores
8   Kemi Ventures  kemi ventures
9     Glow Beauty    glow beauty
10    Glow Beauty    glow beauty
11   Tunde Phones   tunde phones

In [ ]:
#Remove spaces and unwanted characters

query = """
SELECT
    TRIM(Customer_Name)
FROM deliveries;
"""

pd.read_sql(query, connection)

   TRIM(Customer_Name)
0           Ade Stores
1         Bisi Fashion
2           Ade Stores
3        Kemi Ventures
4         Tunde Phones
5         Bisi Fashion
6         Tunde Phones
7           Ade Stores
8        Kemi Ventures
9          Glow Beauty
10         Glow Beauty
11        Tunde Phones

In [ ]:
#To Know the dataset length


query = """
SELECT
    Customer_Name,
    LENGTH(Customer_Name) AS Name_Length
FROM deliveries;
"""

pd.read_sql(query, connection)

    Customer_Name  Name_Length
0      Ade Stores           10
1    Bisi Fashion           12
2      Ade Stores           10
3   Kemi Ventures           13
4    Tunde Phones           12
5    Bisi Fashion           12
6    Tunde Phones           12
7      Ade Stores           10
8   Kemi Ventures           13
9     Glow Beauty           11
10    Glow Beauty           11
11   Tunde Phones           12

Replace

In [ ]:
query = """
SELECT
    Route,
    REPLACE(Route,'/','-') AS Clean_Route
FROM deliveries;
"""

pd.read_sql(query, connection)

            Route    Clean_Route
0    Ibadan-Lagos   Ibadan-Lagos
1    Ibadan-Abuja   Ibadan-Abuja
2    Ibadan-Lagos   Ibadan-Lagos
3   Ibadan-Osogbo  Ibadan-Osogbo
4    Ibadan-Abuja   Ibadan-Abuja
5    Ibadan-Lagos   Ibadan-Lagos
6   Ibadan-Osogbo  Ibadan-Osogbo
7    Ibadan-Abuja   Ibadan-Abuja
8    Ibadan-Lagos   Ibadan-Lagos
9   Ibadan-Ilorin  Ibadan-Ilorin
10   Ibadan-Abuja   Ibadan-Abuja
11   Ibadan-Lagos   Ibadan-Lagos

If...Elif....Else

In [ ]:
query = """
SELECT
    Delivery_ID,
    Profit,

    CASE

        WHEN Profit >= 3000 THEN 'High'

        WHEN Profit >=1500 THEN 'Medium'

        ELSE 'Low'

    END AS Profit_Category

FROM deliveries;
"""

pd.read_sql(query, connection)

    Delivery_ID  Profit Profit_Category
0             1    1800          Medium
1             2    2500          Medium
2             3    2200          Medium
3             4    1800          Medium
4             5    3400            High
5             6    2600          Medium
6             7    2000          Medium
7             8    3100            High
8             9    1950          Medium
9            10    2700          Medium
10           11    2750          Medium
11           12    2350          Medium

In [ ]:
#Write a query that classifies delivery times:

#Less than 45 minutes → "Fast"
#Between 45 and 90 minutes → "Normal"
#More than 90 minutes → "Slow"



query = """
SELECT
    Delivery_ID,
    Delivery_Time_Min,

    CASE

        WHEN Delivery_Time_Min >= 90 THEN 'Slow'

        WHEN Delivery_Time_Min >= 45 THEN 'Normal'

        ELSE 'Fast'

    END AS Delivery_Time_Min_Category

FROM deliveries;
"""

pd.read_sql(query, connection)

    Delivery_ID  Delivery_Time_Min Delivery_Time_Min_Category
0             1                 95                       Slow
1             2                210                       Slow
2             3                100                       Slow
3             4                 55                     Normal
4             5                205                       Slow
5             6                110                       Slow
6             7                 60                     Normal
7             8                195                       Slow
8             9                 90                       Slow
9            10                160                       Slow
10           11                200                       Slow
11           12                105                       Slow

In [ ]:

query = """
SELECT
    Driver,
    COUNT(*) AS Total_Deliveries,
    SUM(Delivery_Fee) AS Total_Revenue,
    SUM(Profit) AS Total_Profit,
    AVG(Delivery_Time_Min) AS Average_Del_Time
FROM deliveries
GROUP BY Driver
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, connection)

  Driver  Total_Deliveries  Total_Revenue  Total_Profit  Average_Del_Time
0   Mary                 4          21700         11750        202.500000
1   John                 5          17400         10900        100.000000
2  David                 3           9800          6500         91.666667

In [ ]:

query = """
SELECT Driver
FROM deliveries
WHERE Profit >
(
    SELECT AVG(Profit)
    FROM deliveries
);
"""

pd.read_sql(query, connection)

In [ ]:
query = """
SELECT
    Driver,
    Delivery_ID,
    Deliverry_Time_Min,
FROM deliveries;
"""

pd.read_sql(query, connection)

DatabaseError: Execution failed on sql '
SELECT
    Driver,
    Delivery_ID,
    Deliverry_Time_Min,
FROM deliveries;
': near "FROM": syntax error

In [ ]:
#A query showing total deliveries by each driver and average delivery time


query = """
SELECT
    Driver,
    COUNT(*) AS Total_Deliveries,
    AVG(Delivery_Time_Min) AS Avg_Delivery_Time
FROM deliveries
GROUP BY Driver
HAVING
    COUNT(*) > 5
    AND AVG(Delivery_Time_Min) < 60
ORDER BY Avg_Delivery_Time ASC;
"""

pd.read_sql(query, connection)

Empty DataFrame
Columns: [Driver, Total_Deliveries, Avg_Delivery_Time]
Index: []

In [ ]:
#Customer with the highest total profit and their rank among all customers based on profit.


query = """
SELECT
    Customer_Name,
    SUM(Profit) AS Total_Profit,
    RANK() OVER(ORDER BY SUM(Profit) DESC) AS Profit_Rank
FROM deliveries
GROUP BY Customer_Name;
"""

pd.read_sql(query, connection)

   Customer_Name  Total_Profit  Profit_Rank
0   Tunde Phones          7750            1
1     Ade Stores          7100            2
2    Glow Beauty          5450            3
3   Bisi Fashion          5100            4
4  Kemi Ventures          3750            5

In [ ]:
query = """
WITH Route_Stats AS
(
    SELECT
        Route,
        AVG(Profit) AS Route_Profit
    FROM deliveries
    GROUP BY Route
)

SELECT
    Route,
    Route_Profit,

    CASE
        WHEN Route_Profit > 2500 THEN 'Excellent'
        WHEN Route_Profit >= 1500 THEN 'Good'
        ELSE 'Poor'
    END AS Performance

FROM Route_Stats

ORDER BY Route_Profit DESC;
"""

pd.read_sql(query, connection)

           Route  Route_Profit Performance
0   Ibadan-Abuja        2937.5   Excellent
1  Ibadan-Ilorin        2700.0   Excellent
2   Ibadan-Lagos        2180.0        Good
3  Ibadan-Osogbo        1900.0        Good

In [ ]:
query = """ 
SELECT 
    Driver, 
    Route, 
    COUNT(Delivery_ID) AS Total_Deliveries, 
    SUM(Delivery_Fee) AS Total_Revenue, 
    SUM(Profit) AS Total_Profit, 
    AVG(Delivery_Time_Min) AS Avg_Delivery_Time,
    RANK() OVER (ORDER BY SUM(Profit) DESC) AS Profit_Rank
FROM deliveries
GROUP BY Driver AND Route
ORDER BY Total_Profit DESC;


"""

pd.read_sql(query, connection)

,Driver,Route,Total_Deliveries,Total_Revenue,Total_Profit,Avg_Delivery_Time,Profit_Rank
0,John,Ibadan-Lagos,12,48900,29150,132.083333,1

In [ ]:
query = """
SELECT
    Driver,
    Route,
    COUNT(Delivery_ID) AS Total_Deliveries,
    SUM(Delivery_Fee) AS Total_Revenue,
    SUM(Profit) AS Total_Profit,
    AVG(Delivery_Time_Min) AS Avg_Delivery_Time,

    RANK() OVER(
        ORDER BY SUM(Profit) DESC
    ) AS Profit_Rank

FROM deliveries

GROUP BY Driver, Route

ORDER BY Profit_Rank;
"""

pd.read_sql(query, connection)

,Driver,Route,Total_Deliveries,Total_Revenue,Total_Profit,Avg_Delivery_Time,Profit_Rank
0,Mary,Ibadan-Abuja,4,21700,11750,202.5,1
1,John,Ibadan-Lagos,5,17400,10900,100.0,2
2,David,Ibadan-Osogbo,2,5300,3800,57.5,3
3,David,Ibadan-Ilorin,1,4500,2700,160.0,4

In [ ]:
df.to_csv(
    "../Datasets/Cleaned/deliveries.csv",
    index=False
)

OSError: Cannot save file into a non-existent directory: '..\Datasets\Cleaned'

In [ ]:
pwd

'c:\\Users\\USER\\Desktop\\Project Exodus\\Python\\Module02_SQL'

In [ ]:
df.to_csv(
    "../../Datasets/Cleaned/deliveries.csv",
    index=False
)

In [ ]:
from pathlib import Path

print(Path.cwd())
print(Path("../../Datasets/Cleaned").resolve())

In [1]:
pwd

'c:\\Users\\USER\\Desktop\\Project Exodus\\Python\\Module02_SQL'

In [2]:
cd ..

c:\Users\USER\Desktop\Project Exodus\Python

In [3]:
cd ..

c:\Users\USER\Desktop\Project Exodus